version: "3.7"

services:
  postgres:
    image: postgres:13
    ports:
      - "5437:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  mq:
    image: rabbitmq:3.9.22-management
    ports:
      - "5673:5672"
      - "15672:15672"
